### ISSUE TITLE
missing exportAs and ignored aliased inputs

### ISSUE THREAD

**Issue by mattrwh** [ike18t/mock_directive#1]
Fyi it seems that this function is stripping out the exportAs argument of the Directive decorator, which causes errors since exportAs allows us to assign directives to # reference variables in our templates, even if they are on the host of a component, by doing:

`<some-component some-directive #someDirective="SomeDirective"></some-component>`

so if `exportAs: "SomeDirective"` is not added to the mock directive we'll get template parsing errors.

Also I noticed issues when aliasing inputs for structural directives.

`div *someStructDir="someInput: true"` will throw an error when mocked if `someStructDirSomeInput` is aliased like `@Input('someStructDirSomeInput') someInput;`

**Comment by mattrwh** [comment]
I can tackle it myself, just wanted to post the issue in case I don't get to it in a timely manner.

**Comment by ike18t** [comment]
Thanks for the feedback!  I don't use directives particularly often so I missed this functionality.  Here you go! 9b42a21488525d026092f7e0646a8335683ddd97

**Comment by mattrwh** [comment]
Thanks!!
